package util

const (
	DoNotEditHead = "// Code generated by goctl. DO NOT EDIT."

	headTemplate = DoNotEditHead + `
// goctl {{.version}}
// Source: {{.source}}`
)

func GetHead(source string) string { _ = "STUB: not implemented"; return "" }
